import type {
	BarreEntry,
	BoxEntry,
	ChordSymbolStyle,
	FillStyle,
	FretNumbering,
	FretValue,
	FretboardBlockConfig,
	FretboardPluginSettings,
	NamingMode,
	NoteEntry,
	NutStyle,
	Orientation,
	PathEntry,
	Shape,
} from "../types";
import { parseRange } from "../parser/range";
import { parseTuning, pitchClassToName, stringPitchClass } from "../music/notes";
import {
	degreeForDelta,
	inferChordSuffix,
	intervalDelta,
	romanForDelta,
	stripTitleMarkers,
} from "../music/intervals";
import { findScaleName } from "../music/scales";

export interface ResolvedNote {
	string: number;
	fret: FretValue;
	label: string;
	shape: Shape;
	finger?: number;
	ghost: boolean;
	className?: string;
	isRoot: boolean;
	/** Note-dot radius in px (System/Global `noteSize` + this note's `sizeAdjust`, times the block's `size`). */
	radius: number;
	/** Label font size in px (System/Global `labelFontSize` + this note's `labelSizeAdjust`, times the block's `size`). */
	labelFontSize: number;
	/** CSS color overriding this note's fill/stroke; undefined uses the theme default. */
	color?: string;
	fillStyle: FillStyle;
}

export interface ResolvedModel {
	orientation: Orientation;
	/** Plain, human-readable title with no embedded typography markers — for display, tests, accessibility. */
	title: string;
	/**
	 * Same content as `title`, but — only when `titleIsAutoGenerated` is true — with
	 * invisible markers embedded around spans that need special SVG typography (see
	 * `TITLE_RAISED_START` et al. in `music/intervals.ts`). The renderer must NOT apply
	 * any character-based typography heuristics to a user-supplied `title:` (arbitrary
	 * text, not necessarily a chord name), so it only parses this field when the title
	 * was actually auto-generated; a custom title is rendered as plain text.
	 */
	titleMarkup: string;
	titleIsAutoGenerated: boolean;
	stringsTotal: number;
	visibleStart: number;
	visibleEnd: number;
	startFret: number;
	fretsWidth: number;
	isRelative: boolean;
	nutStyle: NutStyle;
	fretNumbering: FretNumbering;
	fillStyle: FillStyle;
	stringSpacing: number;
	fretSpacing: number;
	notes: ResolvedNote[];
	barre: BarreEntry[];
	boxes: BoxEntry[];
	paths: PathEntry[];
}

/** Merges a parsed block with plugin-wide defaults into a self-contained render model. */
export function resolveFretboardModel(
	rawConfig: FretboardBlockConfig,
	settings: FretboardPluginSettings
): ResolvedModel {
	// When `startFret` is explicitly given, every other fret number in the block (notes,
	// boxes, paths, barre) is written relative to position 1 — the shape's own first
	// finger position — so the same `notes` block can be reused at any position just by
	// changing `startFret`. 0 (open) and "x" (muted) are never offset: they're always
	// literal. This is a no-op for `startFret` 0 or 1 (and whenever `startFret` is
	// omitted, including when an open string implicitly forces absolute mode), so plain
	// absolute-position shapes written with real fret numbers are unaffected.
	const fretOffset = rawConfig.startFret !== undefined ? Math.max(rawConfig.startFret, 1) - 1 : 0;
	const config = applyFretOffset(rawConfig, fretOffset);

	const tuning = parseTuning(settings.defaultTuning);

	const explicitStrings = new Set(config.notes.map((n) => n.s));
	const maxNoteString = config.notes.reduce((max, n) => Math.max(max, n.s), 0);
	const stringsTotal = Math.max(settings.strings, maxNoteString);

	let visibleStart = 1;
	let visibleEnd = stringsTotal;
	if (config.visible) {
		const range = parseRange(config.visible, "visible");
		visibleStart = range.start;
		visibleEnd = Math.max(range.end, visibleStart);
	}

	// An explicit open string (fret 0) anchors the shape to the nut — it can't be a
	// movable pattern — so its absolute pitch is always known even without `startFret`.
	// Treat that the same as `startFret: 0` for both grid framing and chord naming.
	const hasExplicitOpenString = config.notes.some(
		(n) => n.f === 0 && n.s >= visibleStart && n.s <= visibleEnd
	);
	const isRelative = config.startFret === undefined && !hasExplicitOpenString;
	const frettedValues = config.notes
		.map((n) => n.f)
		.filter((f): f is number => typeof f === "number" && f > 0);
	const startFret = isRelative
		? frettedValues.length > 0
			? Math.min(...frettedValues)
			: 1
		: (config.startFret ?? 0);

	// Auto-expand the grid (like `stringsTotal` above) so a fretted note is never drawn
	// past the last visible column when the user hasn't explicitly sized the grid —
	// e.g. an open Em shape reaching fret 5 shouldn't be clipped by the default
	// 4-fret width just because `frets` wasn't specified.
	const gridStartFretForSizing = Math.max(startFret, 1);
	const maxFrettedNote = frettedValues.length > 0 ? Math.max(...frettedValues) : gridStartFretForSizing;
	const minRequiredWidth = Math.max(maxFrettedNote - gridStartFretForSizing + 1, 1);
	const fretsWidth = config.frets ?? Math.max(settings.fretCount, minRequiredWidth);

	// Fill in notes for strings the YAML omits entirely, per the omitted-string setting.
	const allNotes: NoteEntry[] = [...config.notes];
	if (settings.omittedStringBehavior !== "none") {
		for (let s = visibleStart; s <= visibleEnd; s++) {
			if (!explicitStrings.has(s)) {
				allNotes.push({ s, f: settings.omittedStringBehavior === "open" ? 0 : "x" });
			}
		}
	}

	const visibleNotes = allNotes.filter((n) => n.s >= visibleStart && n.s <= visibleEnd);

	const size = config.size ?? 1;
	const MIN_SPACING = 8;
	const MIN_RADIUS = 3;
	const MIN_LABEL_FONT_SIZE = 4;
	const stringSpacing = Math.max(
		(settings.stringSpacing + (config.stringSpacingAdjust ?? 0)) * size,
		MIN_SPACING
	);
	const fretSpacing = Math.max((settings.fretSpacing + (config.fretSpacingAdjust ?? 0)) * size, MIN_SPACING);

	const rootEntry = visibleNotes.find((n) => n.label === "root" && typeof n.f === "number");
	const rootPitchClass =
		rootEntry && typeof rootEntry.f === "number"
			? stringPitchClass(openStringPitchClass(tuning, rootEntry.s), rootEntry.f)
			: undefined;

	const presentDegrees = new Set<string>();
	const resolvedNotes: ResolvedNote[] = visibleNotes.map((n) => {
		const pitchClass =
			typeof n.f === "number" ? stringPitchClass(openStringPitchClass(tuning, n.s), n.f) : undefined;

		let isRoot = false;
		let autoLabel = "";
		if (pitchClass !== undefined) {
			if (rootPitchClass !== undefined) {
				const delta = intervalDelta(rootPitchClass, pitchClass);
				isRoot = delta === 0;
				presentDegrees.add(degreeForDelta(delta));
				if (settings.labelMode === "interval") {
					autoLabel = degreeForDelta(delta);
				}
			}
			// Absolute pitch is only meaningful when the diagram is anchored to a real
			// fretboard position; a relative/movable shape's actual notes depend on
			// where you play it, so note names would be misleading (unlike intervals,
			// which are shape-relative and stay valid wherever the pattern is played).
			if (settings.labelMode === "note" && !isRelative) {
				autoLabel = pitchClassToName(pitchClass, settings.accidental);
			}
		}

		const hasCustomLabel = n.label !== undefined && n.label !== "root";
		const label = hasCustomLabel ? (n.label as string) : autoLabel;

		const shape: Shape =
			n.shape ?? (isRoot && settings.defaultShape === "circle" ? "square" : settings.defaultShape);

		const classNames: string[] = [];
		if (n.class) classNames.push(n.class);
		if (isRoot) classNames.push("fretboard-note--root");
		if (n.ghost) classNames.push("fretboard-note--ghost");

		const radius = Math.max((settings.noteSize + (n.sizeAdjust ?? 0)) * size, MIN_RADIUS);
		const labelFontSize = Math.max(
			(settings.labelFontSize + (n.labelSizeAdjust ?? 0)) * size,
			MIN_LABEL_FONT_SIZE
		);

		return {
			string: n.s,
			fret: n.f,
			label,
			shape,
			finger: n.finger,
			ghost: n.ghost ?? false,
			className: classNames.length > 0 ? classNames.join(" ") : undefined,
			isRoot,
			radius,
			labelFontSize,
			color: n.color,
			fillStyle: n.fillStyle ?? settings.fillStyle,
		};
	});

	// A slash chord's bass is only meaningful when it differs from the root. "Lowest
	// pitch" is approximated as the highest string number currently sounding (the
	// thickest string among fretted/open notes): this system tracks pitch classes only,
	// not full octave-aware pitch, so it can't otherwise compare absolute pitch height.
	// The interval to the root is well-defined in either mode, but only absolute mode
	// knows a real letter name for it — relative/movable mode instead names the bass by
	// its Roman-numeral degree from the root (e.g. "□m7/bVII"), same reasoning as why
	// note-name labels are suppressed in relative mode above.
	let bassName: string | undefined;
	if (rootPitchClass !== undefined) {
		const soundingNotes = visibleNotes.filter(
			(n): n is NoteEntry & { f: number } => typeof n.f === "number"
		);
		if (soundingNotes.length > 0) {
			const bassNote = soundingNotes.reduce((lowest, n) => (n.s > lowest.s ? n : lowest));
			const bassPitchClass = stringPitchClass(openStringPitchClass(tuning, bassNote.s), bassNote.f);
			if (bassPitchClass !== rootPitchClass) {
				bassName = isRelative
					? romanForDelta(intervalDelta(rootPitchClass, bassPitchClass))
					: pitchClassToName(bassPitchClass, settings.accidental);
			}
		}
	}

	const namingMode = config.namingMode ?? settings.namingMode;
	const chordSymbolStyle = config.chordSymbolStyle ?? settings.chordSymbolStyle;
	const titleIsAutoGenerated = config.title === undefined;
	const titleMarkup =
		config.title ??
		autoTitle(rootPitchClass, presentDegrees, isRelative, settings, namingMode, chordSymbolStyle, bassName);
	const title = stripTitleMarkers(titleMarkup);

	return {
		orientation: config.orientation ?? settings.orientation,
		title,
		titleMarkup,
		titleIsAutoGenerated,
		stringsTotal,
		visibleStart,
		visibleEnd,
		startFret,
		fretsWidth,
		isRelative,
		nutStyle: settings.nutStyle,
		fretNumbering: settings.fretNumbering,
		fillStyle: settings.fillStyle,
		stringSpacing,
		fretSpacing,
		notes: resolvedNotes,
		barre: config.barre ?? [],
		boxes: config.boxes ?? [],
		paths: config.paths ?? [],
	};
}

function applyFretOffset(config: FretboardBlockConfig, offset: number): FretboardBlockConfig {
	if (offset === 0) return config;
	const shift = (f: number): number => (f === 0 ? 0 : f + offset);

	return {
		...config,
		notes: config.notes.map((n) => ({ ...n, f: typeof n.f === "number" ? shift(n.f) : n.f })),
		boxes: config.boxes?.map((box) => {
			const range = parseRange(box.frets, "boxes.frets");
			return { ...box, frets: `${shift(range.start)}-${shift(range.end)}` };
		}),
		paths: config.paths?.map((path) => path.map(([s, f]): [number, number] => [s, shift(f)])),
		barre: config.barre?.map((b) => ({ ...b, fret: shift(b.fret) })),
	};
}

/**
 * Tuning is written low string first (e.g. "E,A,D,G,B,E"), but strings are numbered
 * high string first (string 1 = high e, string 6 = low E), so the mapping is reversed.
 */
function openStringPitchClass(tuning: number[], s: number): number {
	const n = tuning.length;
	const idx = (((n - s) % n) + n) % n;
	return tuning[idx];
}

function autoTitle(
	rootPitchClass: number | undefined,
	presentDegrees: ReadonlySet<string>,
	isRelative: boolean,
	settings: FretboardPluginSettings,
	namingMode: NamingMode,
	chordSymbolStyle: ChordSymbolStyle,
	bassName: string | undefined
): string {
	if (rootPitchClass === undefined) return "";

	// Scale mode only kicks in when the present degrees exactly match a known scale;
	// otherwise there's no single unambiguous scale name, so fall back to naming the
	// chord/arpeggio those notes form (the same thing chord mode always does).
	const scaleName = namingMode === "scale" ? findScaleName(presentDegrees) : undefined;
	if (scaleName !== undefined) {
		return isRelative ? `□ ${scaleName}` : `${pitchClassToName(rootPitchClass, settings.accidental)} ${scaleName}`;
	}

	const suffix = inferChordSuffix(presentDegrees, chordSymbolStyle, bassName);
	if (isRelative) {
		return `□${suffix}`;
	}
	return `${pitchClassToName(rootPitchClass, settings.accidental)}${suffix}`;
}
